### ISSUE TITLE
how is this list.txt generated?

### ISSUE THREAD

**Issue by crazylsj** [Yifei-ZHAO96/Tr-VAD#1]
python train.py --train_data_path 'XXX', found no train_data_path, which is the default specified '... /TIMIT_augmented/train_data/list.txt', how is this list.txt generated? Please answer, thank you

**Comment by Yifei-ZHAO96** [comment]
Hi @crazylsj ,

Please see the updated README, I added the `Data Preprocessing` stage which takes the output of the `Data Preparation` as input and calculates the AFPC feature, and generates the `../TIMIT_augmented/train_data/list.txt`.
